theme = "tokyonight"

[editor.soft-wrap]
enable = true

[editor.file-picker]
hidden = false
git-ignore = false

[keys.normal]
"esc" = ["collapse_selection", ":w"]
"home" = ["goto_file_start"]
"end" = ["goto_file_end"]

[keys.select]
"home" = ["goto_file_start"]
"end" = ["goto_file_end"]
